name: graphics
version: '0.1.1'
synopsis: Experiments with GTK GUIs via Haskell
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2020 Athae Eredh Siniath
license: MIT
tested-with: GHC==8.8

ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
  - base
  - core-data
  - core-text
  - core-program >= 0.2.4
  - haskell-gi-base
  - gi-gtk >= 3.0 && < 4

executables:
  experiment:
    source-dirs:
      - src
    main: GraphicsMain.hs
    ghc-options: -threaded
    other-modules: []

tests:
  check:
    dependencies:
      - hspec
    ghc-options: -threaded
    source-dirs:
      - tests
    main: TestSuite.hs
    other-modules: []
